account/urls.py
from django.urls import path , re_path , include
from . import views


app_name = 'account'


urlpatterns = [
    path('otp_registeration' , views.OtpRegisterationView.as_view() , name="otp"),
    path('check_otp' , views.CheckOtpCode.as_view() , name="check_otp"),
    path('logout' , views.logout_user , name="logout"),
    path('profile' , views.ProfileView.as_view() , name="profile"),
    path('edit_profile' , views.profile_edite , name="edit_profile"),
    path('add/address' , views.AddAdressView.as_view() , name="add_address")
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('' , views.CartDetailView.as_view() , name='cart_main'),
    path('add/<slug:slug>' , views.CartAddView.as_view() , name='cart_add'),
    path('delete/<str:id>' , views.CartDeleteView.as_view() , name='cart_delete'),
    path('order_detail/<int:pk>' , views.OrderDetailView.as_view() , name='order_detail'),
    path('order_add' , views.OrderCreationView.as_view() , name='order_add'),
    path('apply_discount/<int:pk>' , views.ApplyDiscountView.as_view() , name='apply_discount'),
    path('apply_address/<int:pk>' , views.ApplyAddress.as_view() , name='apply_address'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('' , include('home_app.urls')),
    path('shop/' , include('shop.urls')),
    path('account' , include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('contactus/' , include('contactus.urls')),
    path('pay/' , include('pay.urls')),
    path('ckeditor/' , include('ckeditor_uploader.urls')),
    path('about/' , include('about.urls')),
    path('send_sms/' , include('sms_send.urls'))
] + static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('' , views.TestView.as_view() , name="main")
]

pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'

urlpatterns = [
    path('<int:pk>' , views.PayDetail.as_view() , name='main_pay'),
    path('payed/<int:pk>' , views.PasyView.as_view() , name='payed'),
]

cart/models.py
from django.db import models
from account.models import User
from datetime import datetime
from shop.models import Product

class Order(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name='orders' , verbose_name='کاربر')
    total_price = models.IntegerField(default=0, verbose_name='قیمت کلی')
    created_at = models.DateTimeField(auto_now_add=True)
    is_pay = models.BooleanField(default=False , verbose_name='ایا پرداخت شده است ؟')
    addresses = models.TextField(blank=True , null=True, verbose_name='آدرس کاربر')
    image_payed = models.FileField(upload_to='pay/image', null=True , blank=True , verbose_name='عکس پرداخت موفق')
    DeliveryDate = models.DateTimeField(null=True , blank=True , verbose_name='تاریخ تحویل محصول')

    def __str__(self) -> str:
        return self.user.phone
    
    class Meta:
        ordering = ("-created_at",)
        verbose_name = "ثبت درخواست خرید"
        verbose_name_plural = "تنظیمات قسمت ثبت درخواست خرید ها"

class OrderItem(models.Model):
    order = models.ForeignKey(Order , on_delete=models.CASCADE , related_name='items' , verbose_name='کالا درحال انجام')
    product = models.ForeignKey(Product , on_delete=models.CASCADE , related_name='items' , verbose_name='کالا')
    quantity = models.SmallIntegerField(verbose_name='تعداد')
    price = models.PositiveIntegerField(verbose_name='قیمت')

    def __str__(self) -> str:
        return self.order.user.phone
    
    class Meta:
        verbose_name = "پایان ثبت درخواست خرید"
        verbose_name_plural = "تنظیمات قسمت  پایان ثبت درخواست خرید ها"


class DiscountCode(models.Model):
    name = models.CharField(max_length=100 , verbose_name='نام کد تخفیف' , unique=True)
    discount = models.SmallIntegerField(default=0 , verbose_name='مقدار درصد تفیف')
    quantity = models.SmallIntegerField(default=1 , verbose_name='تعداد کد تخفیف')

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = "کد تخفیف"
        verbose_name_plural = "تنظیمات قسمت  کد های تخفیف"

cart/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views.generic import View , TemplateView
from django.urls import reverse
from account.models import Address
from cart.cart_module import Cart
from shop.models import Notification, NotificationPersonal, Product
from .cart_module import Cart
from .models import DiscountCode, Order, OrderItem
from mixins import AddressRequirdMixins, LoginRequirdMixins , LogoutRequirdMixins

class CartDetailView(TemplateView):
    template_name = 'includes/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        if self.request.user.is_authenticated == True:
            context['like'] = self.request.user.likes.all()[:5]
        if self.request.user.is_authenticated == True:
            context['orders'] = self.request.user.orders.all()
        else:
            pass
        return context

class CartAddView(View):
    def post(self , request , slug):
        product = get_object_or_404(Product , slug = slug)
        quantity = request.POST.get('quantity')
        cart = Cart(request)
        cart.add(product , quantity)
        return redirect(reverse('shop:main_shop'))
    
class CartDeleteView(View):
    def get(self , request , id):
        cart = Cart(request)
        cart.delete(id)
        return redirect(reverse('shop:main_shop'))
    
class OrderDetailView(AddressRequirdMixins , View):
    def get(self , request , pk):
        order = get_object_or_404(Order , id=pk)
        return render(request , 'cart/checkout.html' , {'order':order})

class OrderCreationView(AddressRequirdMixins , View):
    def get(self , request):
        cart = Cart(request)
        order = Order.objects.create(user = request.user , total_price = cart.total())
        for item in cart:
            OrderItem.objects.create(order=order , product = item['product'] , quantity = item['quantity'] , price = item['price'])

        cart.remove_cart()
        return redirect('cart:order_detail' , order.id)
    
class ApplyDiscountView(AddressRequirdMixins , View):
    def post(self , request , pk):
        code = request.POST.get('discount_code')
        order = get_object_or_404(Order , id=pk)
        discount_code = get_object_or_404(DiscountCode , name=code)
        if discount_code.quantity == 0 :
            return redirect('cart:order_detail' , order.id)
        order.total_price -= order.total_price * discount_code.discount/100
        order.save()
        discount_code.quantity -= 1
        discount_code.save()
        return redirect('cart:order_detail' , order.id)

class ApplyAddress(AddressRequirdMixins , View):
    def post(self , request , pk):
        order = get_object_or_404(Order , id=pk)
        address = request.POST.get('address')
        order.addresses = address
        order.save()
        NotificationPersonal.objects.create(user = request.user , content = 'در خواست شما به درستی ثبت شد')
        return redirect('pay:main_pay' , order.id)

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
بررسی
{% endblock %}
{% block content %}
<div class="page-title-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="title-content">
                    <h2>بررسی</h2>
                    <ul>
                        <li>
                            <a href="{% url 'home:main' %}">خانه</a>
                        </li>
                        <li>
                            <span>بررسی</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="title-img">
        <img src="{% static "images/page-title1.jpg" %}" alt="About" />
        <img src="{% static "images/shape16.png" %}" alt="Shape" />
        <img src="{% static "images/shape17.png" %}" alt="Shape" />
        <img src="{% static "images/shape18.png" %}" alt="Shape" />
    </div>
</div>

<div class="checkout-area pt-100 pb-70">
    <div class="container">
        <div class="section-title">
            <h2>جزئیات صورتحساب</h2>
        </div>
            <div class="row">
                <div class="col-lg-8">
                    <form action="{% url 'cart:apply_address' order.id %}" method="post">
                        {% csrf_token %}
                        <div class="checkout-billing">
                        {% if request.user.addresses.all %}
                            <div class="form-group">
                                <select name="address">
                                    <option>ادرس*</option>
                                    {% for address in request.user.addresses.all %}
                                    <option>{{address.address}}----------{{address.fullname}}----------{{address.phone}}----------{{address.postal_code}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% else %}
                        <div class="text-center">
                            <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}">
                                <button type="button" class="btn common-btn">
                                    ثبت آدرس
                                    <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                    <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                </button>
                            </a>
                        </div>
                        {% endif %}
                        <div class="text-center">
                            <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}">
                                <button type="button" class="btn common-btn">
                                    ثبت ادرس جدید
                                    <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                    <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                </button>
                            </a>
                        </div>
                        <br>
                            {% if request.user.addresses.all %}
                            <div class="text-center">
                                <button type="submit" class="btn common-btn">
                                    ثبت سفارش
                                    <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                    <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                </button>
                            </div>
                            {% endif %}
                        </div>
                    </form>
                    <form action="{% url 'cart:apply_discount' order.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="discount_code" placeholder="کد تخفیف" />
                        </div>
                        <br>
                        <div class="text-center">
                            <button type="submit" class="btn common-btn">
                                ثبت کد
                                <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                <img src="{% static "images/shape2.png" %}" alt="Shape" />
                            </button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="checkout-order">
                        <h3>سفارش شما:</h3>
                        {% for item in order.items.all %}
                        <ul class="align-items-center">
                            <li>
                                <img src="{{item.product.image.url}}" alt="Checkout" />
                            </li>
                            <li>
                                <h4>{{item.product.title}}</h4>
                            </li>
                            <li>
                                <span>{{item.product.price}} تومان</span>
                            </li>
                        </ul>
                        {% endfor %}
                        <div class="inner">
                            <h4>جمع: <span>{{order.total_price}} تومان</span></h4>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}