account/urls.py
from django.urls import path , re_path , include
from . import views


app_name = 'account'


urlpatterns = [
    path('otp_registeration' , views.OtpRegisterationView.as_view() , name="otp"),
    path('check_otp' , views.CheckOtpCode.as_view() , name="check_otp"),
    path('logout' , views.logout_user , name="logout"),
    path('profile' , views.ProfileView.as_view() , name="profile"),
    path('edit_profile' , views.profile_edite , name="edit_profile"),
    path('add/address' , views.AddAdressView.as_view() , name="add_address")
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('' , views.CartDetailView.as_view() , name='cart_main'),
    path('add/<slug:slug>' , views.CartAddView.as_view() , name='cart_add'),
    path('delete/<str:id>' , views.CartDeleteView.as_view() , name='cart_delete'),
    path('order_detail/<int:pk>' , views.OrderDetailView.as_view() , name='order_detail'),
    path('order_add' , views.OrderCreationView.as_view() , name='order_add'),
    path('apply_discount/<int:pk>' , views.ApplyDiscountView.as_view() , name='apply_discount'),
    path('apply_address/<int:pk>' , views.ApplyAddress.as_view() , name='apply_address'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('' , include('home_app.urls')),
    path('shop/' , include('shop.urls')),
    path('account' , include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('contactus/' , include('contactus.urls')),
    path('pay/' , include('pay.urls')),
    path('ckeditor/' , include('ckeditor_uploader.urls')),
    path('about/' , include('about.urls')),
    path('send_sms/' , include('sms_send.urls'))
] + static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('' , views.TestView.as_view() , name="main")
]

pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'

urlpatterns = [
    path('<int:pk>' , views.PayDetail.as_view() , name='main_pay'),
    path('payed/<int:pk>' , views.PasyView.as_view() , name='payed'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('' , views.ProductView.as_view() , name="main_shop"),
    path('detail/<slug:slug>' , views.ProductDetail.as_view() , name="shop_detail"),
    path('category/<int:pk>', views.CategoryDetails.as_view() , name='category_detail'),
    path('like/<slug:slug>/<int:pk>' , views.like , name='like'),
    path('search' , views.SearchBox.as_view() , name='search'),
    path('acceptterms' , views.AcceptTerms.as_view() , name='acceptterms'),
]

shop/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.text import slugify
from account.models import User

class Category(models.Model):
    fontasswoem = models.CharField(max_length=500 , null=True , blank=True , verbose_name="عکس دسته بندی")
    title = models.CharField(max_length=150 , null=True , blank=True , verbose_name="نام دسته بندی")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = "تنظیمات قسمت دسته بندی"

class Tags(models.Model):
    title = models.CharField(max_length=150 , null=True , blank=True , verbose_name="نام برچسب")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'برچسب'
        verbose_name_plural = "تنظیمات قسمت  برچسب ها"


class objects_manager(models.Manager):
    def status(self):
        return self.filter(status=True)
class Product(models.Model):
    title = models.CharField(max_length=150 , null=True , blank=True , verbose_name="نام کالا")
    english_title = models.CharField(max_length=150 , null=True , blank=True , verbose_name="نام اینگلیسی کالا")
    slug = models.SlugField(null=True , blank=True)
    discription = models.TextField(null=True , blank=True , verbose_name="توضیحات کوتاه")
    price = models.SmallIntegerField(null=True , blank=True , verbose_name="قیمت کالا")
    code = models.SmallIntegerField(null=True , blank=True , verbose_name="کد کالا" , unique=True)
    category = models.ManyToManyField(Category , verbose_name="دسته بندی محصول" , related_name="products")
    image = models.ImageField(upload_to='shop/products' , verbose_name="عکس کالا اصلی" , null=True , blank=True)
    image1 = models.ImageField(upload_to='shop/products' , verbose_name="1عکس کالا" , null=True , blank=True)
    image2 = models.ImageField(upload_to='shop/products' , verbose_name="2عکس کالا" , null=True , blank=True)
    image3 = models.ImageField(upload_to='shop/products' , verbose_name="3عکس کالا" , null=True , blank=True)
    tags = models.ManyToManyField(Tags , verbose_name="برچسب")
    content = RichTextUploadingField(null=True , blank=True , verbose_name='توضیحات بیشتر')
    tip1 = models.CharField(max_length=12000 , null=True , blank=True , verbose_name='نکته1')
    tip2 = models.CharField(max_length=12000 , null=True , blank=True , verbose_name='نکته2')
    tip3 = models.CharField(max_length=12000 , null=True , blank=True , verbose_name='نکته3')
    tip4 = models.CharField(max_length=12000 , null=True , blank=True , verbose_name='نکته4')
    tip5 = models.CharField(max_length=12000 , null=True , blank=True , verbose_name='نکته5')
    status = models.BooleanField(default=True , verbose_name="ایا موجود است ؟")
    special = models.BooleanField(default=False , verbose_name="ایا کالا ویژه است ؟")
    on_sale = models.BooleanField(default=False , verbose_name="ایا کالای حراج است ؟")
    objects = objects_manager()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ('-created',)
        verbose_name = 'محصولات'
        verbose_name_plural = "تنظیمات قسمت محصولات"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Product , self).save(*args, **kwargs)

class Comments(models.Model):
    user = models.ForeignKey(User , related_name="comment" , on_delete=models.CASCADE , verbose_name = 'کاربر')
    products = models.ForeignKey(Product , related_name="comment" , on_delete=models.CASCADE, verbose_name = 'کالا ها')

    parent = models.ForeignKey('self' , on_delete=models.CASCADE , related_name = 'replies' , null=True , blank=True, verbose_name = 'پست جواب داده شده')

    message = RichTextUploadingField(null=True, blank=True, verbose_name = 'نظرات')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}-{self.products.title}'

    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = "تنظیمات قسمت نظرات"
        ordering = ('-created',)

class Like(models.Model):
    users = models.ForeignKey(User , related_name='likes' , on_delete=models.CASCADE , verbose_name = 'کاربر')
    products = models.ForeignKey(Product , related_name='likes' , on_delete=models.CASCADE , verbose_name = 'کالا ها')
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.users.username} - {self.products.title}"

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "تنظیمات قسمت لایک ها"
        ordering = ("-created",)

class Notification(models.Model):
    user = models.ManyToManyField(User , related_name='notifications' , verbose_name="انتخاب کاربر")
    content = RichTextUploadingField(verbose_name="متن اعلان")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'اعلان'
        verbose_name_plural = 'اعلان ها'
        ordering = ('-created',)

class NotificationPersonal(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name='notification_personal' , verbose_name="انتخاب کاربر")
    content = RichTextUploadingField(verbose_name="متن اعلان")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'اعلان'
        verbose_name_plural = 'اعلان های شخصی کاربران'
        ordering = ('-created',)

class AcceptTermsModel(models.Model):
    discription_of_acceptterms = RichTextUploadingField(null=True , blank=True , verbose_name = 'توضیحات درباره ی شرایط سایت')
    target_of_acceptterms1 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 1 از گذاشتن شرایط و ...')
    target_of_acceptterms2 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 2 از گذاشتن شرایط و ...')
    target_of_acceptterms3 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 3 از گذاشتن شرایط و ...')
    target_of_acceptterms4 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 4 از گذاشتن شرایط و ...')
    target_of_acceptterms5 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 5 از گذاشتن شرایط و ...')
    target_of_acceptterms6 = models.TextField(null=True , blank=True , verbose_name='هدف شماره 6 از گذاشتن شرایط و ...')

    def __str__(self) -> str:
        return self.discription_of_acceptterms
    
    class Meta:
        verbose_name = 'شرایط و ضوابط'
        verbose_name_plural = 'تنظیمات شرایط و ضوابط'

shop/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import  View , TemplateView , ListView , DetailView
from django.core.paginator import Paginator
from contactus.models import Contacts
from .models import Comments, Like, Product , Category , AcceptTermsModel

class ProductView(ListView):
    template_name = "shop/shop.html"
    model = Product
    context_object_name = 'products'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

class ProductDetail(DetailView):
    template_name = 'shop/single-product.html'
    model = Product
    context_object_name = 'products'
    def get_context_data(self ,*args , **kwargs):
        context = super().get_context_data(*args , **kwargs)
        queryset = Product.objects.get(slug = self.object.slug)
        queryset.save()
        if self.request.user.is_authenticated == True:
            if self.request.user.likes.filter(products__english_title = self.object.english_title , users_id = self.request.user.id).exists():
                context['is_liked'] = True
            else:
                context['is_liked'] = False
        else:
            pass
        return context
    def post(self,request,slug):
        products = Product.objects.get(slug=slug)
        parent_id = request.POST.get('parent_id')
        message = request.POST.get('message')
        Comments.objects.create(message=message, parent_id=parent_id , products=products , user=request.user)
        return redirect('shop:shop_detail' , slug)

class CategoryDetails(View):
    queryset = None
    template_name = 'shop/shop.html'
    def get(self, request , pk):
        queryset = get_object_or_404(Category , id=pk)
        objects = queryset.products.all()
        category = Category.objects.all()
        return render (request , self.template_name , {'id':pk , 'products':objects , 'category':category})
    
def like(request , slug , pk):
    try:
        like = Like.objects.get(products__slug = slug , users_id=request.user.id)
        like.delete()
    except:
        Like.objects.create(products_id=pk , users_id = request.user.id)
    return redirect('shop:shop_detail' , slug)

class SearchBox(TemplateView):
    queryset = None
    template_name = "shop/shop.html"
    def get(self, request, *args, **kwargs):
        q = request.GET.get('q')
        queryset =  Product.objects.filter(title__icontains = q)
        return render(request, self.template_name, {'products': queryset})
    
class AcceptTerms(TemplateView):
    template_name = 'shop/terms-conditions.html'
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['acceptterms'] = AcceptTermsModel.objects.all()
        return context

shop/templates/shop/shop.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
فروشگاه
{% endblock %}
{% block content %}
<div class="page-title-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="title-content">
                    <h2>فروشگاه</h2>
                    <ul>
                        <li>
                            <a href="{% url 'home:main' %}">خانه</a>
                        </li>
                        <li>
                            <span>فروشگاه</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="title-img">
        <img src="{% static "images/page-title1.jpg" %}" alt="About" />
        <img src="{% static "images/shape16.png" %}" alt="Shape" />
        <img src="{% static "images/shape17.png" %}" alt="Shape" />
        <img src="{% static "images/shape18.png" %}" alt="Shape" />
    </div>
</div>

<div class="products-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="sorting-menu">
                    <ul>
                        <li class="filter" data-filter="{% if request.resolver_match.url_name == 'main_shop'%}all{% endif %}">
                            <a href="{% url 'shop:main_shop' %}">
                                <div class="products-thumb">
                                    <img src="{% static "images/products/shape1.png" %}" alt="Shape" />
                                    <img src="{% static "images/products/shape2.png" %}" alt="Shape" />
                                    <i class="flaticon-square"></i>
                                    <span>همه</span>
                                </div>
                            </a>
                        </li>
                    {% for data in category %}
                    <li class="filter" data-filter="{% if request.resolver_match.url_name == 'category_detail/{{data.id}}'%}all{% endif %}">
                        <a href="{% url 'shop:category_detail' data.id %}">
                            <div class="products-thumb">
                                <img src="{% static "images/products/shape1.png" %}" alt="Shape" />
                                <img src="{% static "images/products/shape2.png" %}" alt="Shape" />
                                <i class="{{ data.fontasswoem }}"></i>
                                <span>{{data.title}}</span>
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div id="Container" class="row">
                    {% for data in products %}
                    <div class="col-sm-6 col-lg-4 mix sofa bed">
                        <div class="products-item">
                            <div class="top">
                                {% if data.on_sale == True %}
                                <a class="product-type" href="">حراج</a>
                                {% endif %}
                                {% if data.special == True %}
                                <a class="product-type" href="">ویژه</a>
                                {% endif %}
                                <a class="wishlist" href="#">
                                    <i class="bx bx-heart"></i>
                                </a>
                                <img src="{{ data.image.url }}" alt="Products" />
                                <div class="inner">
                                    <h3>
                                        <a href="{% url 'shop:shop_detail' data.slug %}">{{data.title}}</a>
                                    </h3>
                                    <span>{{data.price}} تومان</span>
                                </div>
                            </div>
                            <div class="bottom">
                                <a class="cart-text" href="#">سبد خرید</a>
                                <i class="bx bx-plus" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"></i>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="products-area pb-70">
    <div class="container">
        <div class="section-title">
            <h2>پرفروش ترین محصولات</h2>
        </div>
        <div class="row">
            {% for data in products %}
                {% if data.likes.count >= 5 %}
                <div class="col-sm-6 col-lg-3">
                    <div class="products-item">
                        <div class="top">
                            <a class="wishlist" href="#">
                                <i class="bx bx-heart"></i>
                            </a>
                            <img src="{{data.image.url}}" alt="Products" />
                            <div class="inner">
                                <h3>
                                    <a href="single-product.html">{{data.title}}</a>
                                </h3>
                                <span>{{data.price}} تومان</span>
                            </div>
                        </div>
                        <div class="bottom">
                            <a class="cart-text" href="#">سبد خرید</a>
                            <i class="bx bx-plus"></i>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/single-product.html
{% extends 'base.html' %}
{% load static %}
{% load ratings %}
{% block title %}
{{products.title}}
{% endblock %}
{% block content %}
<div class="page-title-area">
            <div class="d-table">
                <div class="d-table-cell">
                    <div class="container">
                        <div class="title-content">
                            <h2>جزئیات محصول</h2>
                            <ul>
                                <li>
                                    <a href="{% url 'home:main' %}">خانه</a>
                                </li>
                                <li>
                                    <span>جزئیات محصول</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="title-img">
                <img src="{% static "images/page-title2.jpg" %}" alt="About" />
                <img src="{% static "images/shape16.png" %}" alt="Shape" />
                <img src="{% static "images/shape17.png" %}" alt="Shape" />
                <img src="{% static "images/shape18.png" %}" alt="Shape" />
            </div>
        </div>

        <div class="product-details-area ptb-100">
            <div class="container">
                <div class="top">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <div class="outer">
                                <div class="row">
                                    <div class="col-4 col-sm-3 col-lg-3">
                                        <div id="thumbs" class="owl-carousel owl-theme">
                                            <div class="item">
                                                <div class="top-img">
                                                    <img src="{{products.image1.url}}" alt="Product" />
                                                </div>
                                            </div>
                                            <div class="item">
                                                <div class="top-img">
                                                    <img src="{{products.image2.url}}" alt="Product" />
                                                </div>
                                            </div>
                                            <div class="item">
                                                <div class="top-img">
                                                    <img src="{{products.image3.url}}" alt="Product" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-8 col-sm-9 col-lg-9">
                                        <div id="big" class="owl-carousel owl-theme">
                                            <div class="item">
                                                <div class="top-img">
                                                    <img src="{{products.image.url}}" alt="Product" />
                                                </div>
                                            </div>
                                            <div class="top-img">
                                                <img src="{{ products.image1.url }}" alt="Product" />
                                            </div>
                                            <div class="top-img">
                                                <img src="{{products.image2.url}}" alt="Product" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="top-content">
                                <h2>{{products.title}}</h2>
                                {% ratings products %}
                                <ul class="reviews">
                                    <li>
                                        <span>(2 نظرات)</span>
                                    </li>
                                    <li>
                                        <h3>{{products.price}} تومان</h3>
                                    </li>
                                </ul>
                                <p>{{products.discription|safe}}</p>
                                <ul class="tag">
                                    <li>کد: <span>{{products.code}}</span></li>
                                    <li>دسته بندی: <span>{{products.category.first}}</span></li>
                                    <li>برچسب: <span>{{products.tags.first}}</span></li>
                                    {% if products.status == True %}
                                    <li>وضعیت: <span>موجود</span></li>
                                    {% else %}
                                    <li>وضعیت: <span>نا موجود</span></li>
                                    {% endif %}
                                </ul>
                                <form method="post" action="{% url 'cart:cart_add' products.slug %}" onclick="JSalert()">
                                    {% csrf_token %}
                                    <ul class="cart">
                                        <li>
                                            <ul class="number">
                                                <li>
                                                    <span class="minus">-</span>
                                                    <input type="text" name="quantity" value="1"/>
                                                    <span class="plus">+</span>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <button style="border: none;background: none;" type="submit">
                                                <a class="common-btn">
                                                    سبد خرید
                                                    <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                                    <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                                </a>
                                            </button>
                                        </li>
                                    </ul>
                                </form>
                                {% if request.user.is_authenticated == True %}
                                    {% if is_liked %}
                                    <a id="like-post" class="wishlist-btn" href="{% url 'shop:like' products.slug products.id %}"><i class="fa-solid fa-heart"></i></a>                                   
                                    {% else %}
                                    <a id="like-post" class="wishlist-btn" href="{% url 'shop:like' products.slug products.id %}"><i class="fa-regular fa-heart"></i></a></a>
                                    {% endif %}
                                {% else %}
                                <p class="alert alert-danger">برای لایک کردن پست اول در <a href="{% url 'account:otp' %}">سایت ثبت نام</a> کنید</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bottom">
                    <ul class="nav nav-pills" id="pills-tab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">توضیحات</a>
                        </li>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">نظرات</a>
                        </li>
                        <li class="nav-item" role="presentation"></li>
                    </ul>

                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <div class="bottom-description">
                                <p>
                                    {{products.content|safe}}
                                </p>
                                <ul>
                                    <li><span></span>{{products.tip1}}</li>
                                    <li><span></span>{{products.tip2}}</li>
                                    <li><span></span>{{products.tip3}}</li>
                                    <li><span></span>{{products.tip4}}</li>
                                    <li><span></span>{{products.tip5}}</li>
                                </ul>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <div class="bottom-comment">
                                <ul class="comments">
                                {% for comment in products.comment.all %}
                                    {% if comment.parent == None %}
                                    <li>
                                        <img src="{% static "images/main-photo.svg" %}" alt="Blog" />
                                        <h4>{{ comment.user.phone }}</h4>
                                        <span>{{comment.created}}</span>
                                        <p>
                                            {{comment.message|safe}}
                                        </p>
                                        <ul class="reviews">
                                            <li>
                                                {% ratings comment %}
                                            </li>
                                        </ul>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                                </ul>
                            </div>
                            <div class="bottom-review">
                                <h3>ارسال نظرات</h3>
                                {% if request.user.is_authenticated == True %}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="hidden" name="parent_id" id="parent_id" class="form-control" value=""/>
                                    </div>
                                    <div class="form-group">
                                        <textarea id="your-comments" name="message" rows="8" class="form-control" placeholder="نظرات"></textarea>
                                    </div>
                                    <button type="submit" class="btn common-btn">
                                        ارسال نظر
                                        <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                        <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                    </button>
                                </form>
                                {% else %}
                                <p class="alert alert-danger">برای  کامنت گذاشتن پست اول در <a href="{% url 'account:otp' %}">سایت ثبت نام</a> کنید</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}     