config/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('' , include('home_app.urls')),
    path('shop/' , include('shop.urls')),
    path('account' , include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('contactus/' , include('contactus.urls')),
    path('pay/' , include('pay.urls')),
    path('ckeditor/' , include('ckeditor_uploader.urls')),
    path('about/' , include('about.urls')),
    path('send_sms/' , include('sms_send.urls'))
] + static(settings.MEDIA_URL , document_root= settings.MEDIA_ROOT)

contactus/urls.py
from django.urls import path
from .import views

app_name = 'contactus'

urlpatterns = [
    path('' , views.ContactUs.as_view() , name='contact_main'),
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('' , views.TestView.as_view() , name="main")
]

pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'

urlpatterns = [
    path('<int:pk>' , views.PayDetail.as_view() , name='main_pay'),
    path('payed/<int:pk>' , views.PasyView.as_view() , name='payed'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('' , views.ProductView.as_view() , name="main_shop"),
    path('detail/<slug:slug>' , views.ProductDetail.as_view() , name="shop_detail"),
    path('category/<int:pk>', views.CategoryDetails.as_view() , name='category_detail'),
    path('like/<slug:slug>/<int:pk>' , views.like , name='like'),
    path('search' , views.SearchBox.as_view() , name='search'),
    path('acceptterms' , views.AcceptTerms.as_view() , name='acceptterms'),
]

contactus/models.py
from django.db import models

class objects_manager(models.Manager):
    def status(self):
        return self.filter(status=True)
class ContactUsModels(models.Model):
    username = models.CharField(max_length=200 , null=True , blank=True , verbose_name='نام')
    email = models.EmailField(null=True , blank=True , verbose_name='ایمیل کاربر')
    phone_number = models.IntegerField(null=True , blank=True , verbose_name='شماره تلفن کاربر')
    subject = models.CharField(max_length=1000 , null=True , blank=True , verbose_name=' موضوع ')
    message = models.TextField(null=True , blank=True , verbose_name=' پیام ')
    status = models.BooleanField(default=False , null=True , blank=True , verbose_name=' ایا چک شده است ؟ ')
    is_Accept_terms = models.BooleanField(default=False , verbose_name='پذیرفتن شرایط')
    objects = objects_manager()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'تماس با ما'
        verbose_name_plural = "تنظیمات قسمت تماس با ما" 

class Contacts(models.Model):
    address = models.CharField(max_length=1000 , null=True , blank=True , verbose_name='ادرس محل کار') 
    phone_number = models.BigIntegerField(null=True , blank=True , verbose_name='تلفن محل کار')
    email_address = models.EmailField(null=True , blank=True , verbose_name='ایمیل محل کار')
    facebook = models.CharField(max_length=10000 , null=True , blank=True , verbose_name='ادرس فیس بوک')
    twiter = models.CharField(max_length=10000 , null=True , blank=True , verbose_name='ادرس تویتر')
    linkdin = models.CharField(max_length=10000 , null=True , blank=True , verbose_name='ادرس لینک دین')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'اطلاعات تماس'
        verbose_name_plural = "تنظیمات قسمت اطلاعات تماس" 

contactus/views.py
from django.shortcuts import render , redirect
from django.views.generic import TemplateView , FormView
from django.urls import reverse_lazy , reverse
from .form import ContactForm
from .models import ContactUsModels , Contacts
from mixins import LoginRequirdMixins , LogoutRequirdMixins


class ContactUs(LogoutRequirdMixins , FormView):
    template_name = 'contactus/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('home:main')
    def form_valid(self, form):
        cd = form.cleaned_data
        ContactUsModels.objects.create(username=cd['username'] , email=cd['email'] , phone_number=cd['phone_number'] , subject = cd['subject'] , message = cd['message'] , is_Accept_terms = cd['is_Accept_terms'])
        return redirect(reverse_lazy('home:main'))
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = Contacts.objects.all()
        return context

contactus/templates/contactus/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
تماس با ما
{% endblock %}
{% block content %}
<div class="page-title-area">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="container">
                <div class="title-content">
                    <h2>تماس با ما</h2>
                    <ul>
                        <li>
                            <a href="{% url 'home:main' %}">خانه</a>
                        </li>
                        <li>
                            <span>تماس با ما</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="title-img">
        <img src="{% static "images/page-title5.jpg" %}" alt="About" />
        <img src="{% static "images/shape16.png" %}" alt="Shape" />
        <img src="{% static "images/shape17.png" %}" alt="Shape" />
        <img src="{% static "images/shape18.png" %}" alt="Shape" />
    </div>
</div>

<div class="contact-area pt-100 pb-70">
    <div class="container">
        <div class="section-title">
            <h2>با ما در تماس باشید</h2>
        </div>
        <div class="row">
            <div class="col-sm-6 col-lg-8">
                <div id="contactForm2">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.errors}}
                        <div class="row">
                            <div class="col-6 col-lg-6">
                                <div class="form-group">
                                    {{form.username}}
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-6">
                                <div class="form-group">
                                    {{form.email}}
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-6">
                                <div class="form-group">
                                    {{form.phone_number}}
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-6 col-lg-6">
                                <div class="form-group">
                                    {{form.subject}}
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    {{form.message}}
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <div class="form-check">
                                        {{form.is_Accept_terms}}
                                        <label class="form-check-label" for="flexCheckDefault3"> من همه <a href="{% url 'shop:acceptterms' %}">شرایط و ضوابط</a> را می پذیرم</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <button type="submit" class="btn common-btn">
                                        ارسال پیام
                                        <img src="{% static "images/shape1.png" %}" alt="Shape" />
                                        <img src="{% static "images/shape2.png" %}" alt="Shape" />
                                    </button>
                                    <div id="msgSubmit" class="h3 text-center hidden"></div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            {% for data in contacts %}
            <div class="col-sm-6 col-lg-4">
                <div class="contact-info">
                    <h3>اطلاعات تماس:</h3>
                    <ul class="info">
                        <li>
                            <i class="flaticon-pin"></i>
                            <a href="#">{{data.address}}</a>
                        </li>
                        <li>
                            <i class="flaticon-phone-call"></i>
                            <a href="tel:0217654321">{{data.phone_number}}</a>
                        </li>
                        <li>
                            <i class="flaticon-email"></i>
                            <a href="#">
                                <span>{{data.email_address}}</span>
                            </a>
                        </li>
                    </ul>
                    <div class="social-links">
                        <ul>
                            <li>
                                <a href="{{data.facebook}}" target="_blank">
                                    <i class="bx bxl-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{{data.twiter}}" target="_blank">
                                    <i class="bx bxl-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{{data.linkdin}}" target="_blank">
                                    <i class="bx bxl-linkedin"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}